# frontend/Dockerfile.dev
FROM node:18-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

# Expose Vite dev server port
EXPOSE 5173

# Run Vite in a way Docker keeps the container alive
CMD sh -c "npm run dev -- --host 0.0.0.0 --port 5173 --force"
